#cloud-config
fdqn: ${fqdn}
users:
  - name: mhutter
    groups: ['sshlogin']
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFV+NEZgxUVz+jWA4dxuFIKlUT1vdhsVD12ewx/5zz8u rokkit2021

phone_home:
  url: https://c728a5146e67f85dcc0038eeb3cbf1e3.m.pipedream.net
  post:
    - pub_key_ed25519
    - instance_id
    - hostname
    - fdqn
  tries: 10
